Repository dhis2/dhis2-android-sdk, pull requests merged in 2018-10, with the labels that each got.

#399 sort-order-start-1: start sort order in 1 like server
  core/src/main/java/org/hisp/dhis/android/core/common/OrderedLinkModelHandlerImpl.java
Labels: enhancement

#397 Deleted enrollments sync
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
Labels: enhancement

#398 Category options order
  core/src/main/assets/migrations/23.yaml
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionLinkModel.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryOptionLinkStore.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryHandler.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/test/java/org/hisp/dhis/android/core/category/CategoryHandlerShould.java
Labels: enhancement

#406 cursor-close: close cursors
  core/src/main/java/org/hisp/dhis/android/core/common/ForeignKeyCleaner.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
Labels: bug

#405 4.4-foreign-keys: set FKs only on android 4.4
  build.gradle
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Labels: enhancement

#408 category-category-combos-order: add sort order
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkStoreShould.java
  core/src/main/assets/migrations/24.yaml
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkModel.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCategoryComboLinkStore.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/test/java/org/hisp/dhis/android/core/category/CategoryComboHandlerShould.java
Labels: enhancement

#409 Data elements data set sections order
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelShould.java
  core/src/main/assets/migrations/25.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModel.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkStore.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilderShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
Labels: enhancement

#412 Tei error management
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPI29Should.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPI30Should.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceAPIShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceUtils.java
  core/src/main/java/org/hisp/dhis/android/core/D2.java
  core/src/main/java/org/hisp/dhis/android/core/ObjectMapperFactory.java
  core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
  core/src/main/java/org/hisp/dhis/android/core/common/APICallExecutor.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstance.java
Labels: bug

#427 Androsdk 390
  core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreDataElementOperandListColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreObjectWithUidListColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/Section.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionFields.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionStore.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionTableInfo.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionModelBuilderShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionShould.java
Labels: refactor

#425 [ANDROSDK-374] Close all cursors in tests and add code to fail when c…
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/common/ForeignKeyCleanerShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/DatabaseAssert.java
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/DbOpenHelperShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/migrations/DataBaseMigrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramRuleActionStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramRuleVariableStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageSectionStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/user/UserAuthenticateCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCredentialsStoreShould.java
  core/src/main/java/org/hisp/dhis/android/core/D2.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/SqliteCheckerUtility.java
Labels: enhancement

#431 [ANDROSDK-393] DataValue: Move exists checking from Handler to Store
  core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueHandler.java
  core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueHandlerImpl.java
Labels: refactor

#444 [ANDROSDK-406] Remove attributeCategoryOptions from Event
  core/src/androidTest/assets/event_1_with_all_data_values.json
  core/src/androidTest/assets/events.json
  core/src/androidTest/assets/events_1.json
  core/src/androidTest/assets/events_1_with_removed_data_values.json
  core/src/androidTest/assets/events_2.json
  core/src/androidTest/assets/tracked_entity_instance.json
  core/src/androidTest/assets/tracked_entity_instance_with_removed_data.json
  core/src/androidTest/assets/two_events_first_good_second_wrong_foreign_key.json
  core/src/androidTest/java/org/hisp/dhis/android/core/common/EventCallFactory.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventStoreShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/api/TrackedEntityInstanceUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngineIntegrationShould.java
  core/src/main/assets/migrations/28.yaml
  core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/event/Event.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventModel.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventPostCall.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventQuery.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventService.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventStore.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
  core/src/test/java/org/hisp/dhis/android/core/event/EventHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/event/EventShould.java
Labels: bug

#446 [ANDROSDK-395] Refactor OldSearchOrganisationUnitCall
  core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCall.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/SearchOrganisationUnitOnDemandCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePersistenceCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceRelationshipPersistenceCall.java
Labels: refactor

#438 [ANDROSDK-400] Unified class DataSet
  core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
  core/src/main/java/org/hisp/dhis/android/core/common/AccessHelper.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/AccessColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/DataInputPeriodListColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/DataSetElementListAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/SectionListAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetFields.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetStore.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetTableInfo.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnit.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserFields.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetModelBuilderShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetShould.java
Labels: refactor

#452 [ANDROSDK-407] Fix not closed cursor
  core/src/main/java/org/hisp/dhis/android/core/common/StoreWithStateImpl.java
Labels: bug

#459 [ANDROSDK-372] Ensure not adding children to null objects, fix code
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryModuleMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/ChildrenAppenderExecutor.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipObjectRepository.java
Labels: bug
