Repository dhis2/dhis2-android-sdk, pull requests merged in 2018-11, with the labels that each got.

#465 [ANDROSDK-435] Add Legend set and Legend store tests.
  core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendSetStoreIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/legendset/LegendStoreIntegrationShould.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/legend/LegendSamples.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/legend/LegendSetSamples.java
Labels: enhancement

#467 [ANDROSDK-432] Unified class ProgramStageSection
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageSectionStoreIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageSectionStoreShould.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreDataElementListColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/IgnoreProgramIndicatorListAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramStageSectionRenderingColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageFields.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionFields.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionStore.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionTableInfo.java
  core/src/main/java/org/hisp/dhis/android/core/wipe/WipeModuleImpl.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/program/ProgramStageSectionSamples.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandlerShould.java
Labels: refactor

#471 [ANDROSDK-438] Remove hardcoded JSON from Java instrumentation tests
  core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
Labels: refactor

#477 [ANDROSDK-443] Move toContentValues from BaseModel to Model
  core/src/main/java/org/hisp/dhis/android/core/category/Category.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCombo.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOption.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCombo.java
  core/src/main/java/org/hisp/dhis/android/core/common/BaseModel.java
  core/src/main/java/org/hisp/dhis/android/core/common/Model.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/Section.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/note/Note.java
  core/src/main/java/org/hisp/dhis/android/core/indicator/Indicator.java
  core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorType.java
  core/src/main/java/org/hisp/dhis/android/core/legendset/Legend.java
  core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSet.java
  core/src/main/java/org/hisp/dhis/android/core/option/Option.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionSet.java
  core/src/main/java/org/hisp/dhis/android/core/program/Program.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicator.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipType.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityType.java
  core/src/main/java/org/hisp/dhis/android/core/user/User.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserCredentials.java
Labels: refactor

#481 [ANDROSDK-448] Ensure IdAdapters don't try to create objects with null uid
  core/src/main/java/org/hisp/dhis/android/core/data/database/CategoryComboWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/IdentifiableObjectColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/ObjectWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/OptionSetWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/OrganisationUnitWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramStageWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/ProgramWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/RelationshipTypeWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/TrackedEntityInstanceWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/TrackedEntityTypeWithUidColumnAdapter.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/UserWithUidColumnAdapter.java
Labels: bug

#482 [ANDROSDK-446] Metadata performance evaluation
  core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/common/UidsHelper.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/PerformanceHintsService.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModule.java
  core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
  core/src/test/java/org/hisp/dhis/android/core/systeminfo/PerformanceHintsServiceShould.java
Labels: enhancement

#483 [ANDROSDK-449] Remove explicit id in unified classes
  core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/category/Category.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryCombo.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOption.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionCombo.java
  core/src/main/java/org/hisp/dhis/android/core/common/BaseIdentifiableObject.java
  core/src/main/java/org/hisp/dhis/android/core/common/BaseModel.java
  core/src/main/java/org/hisp/dhis/android/core/common/Model.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/Section.java
  core/src/main/java/org/hisp/dhis/android/core/indicator/Indicator.java
  core/src/main/java/org/hisp/dhis/android/core/indicator/IndicatorType.java
  core/src/main/java/org/hisp/dhis/android/core/legendset/Legend.java
  core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSet.java
  core/src/main/java/org/hisp/dhis/android/core/option/Option.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionSet.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnit.java
  core/src/main/java/org/hisp/dhis/android/core/program/Program.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicator.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRule.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipType.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValue.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityType.java
  core/src/main/java/org/hisp/dhis/android/core/user/User.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserCredentials.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/organisationunit/OrganisationUnitSamples.java
Labels: enhancement

#485 [ANDROSDK-433] Unified classTreackedEntityAttributeReservedValue
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValue.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreInterface.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueTableInfo.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilderShould.java
Labels: refactor

#489 [ANDROSDK-452] TEA Reserved Values optimization
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/D2.java
  core/src/main/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorCode.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeModel.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueQuery.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueService.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStoreInterface.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueTableInfo.java
  core/src/test/java/org/hisp/dhis/android/core/arch/db/WhereClauseBuilderShould.java
Labels: enhancement

#495 [ANDROSDK-460] Move PerformanceHintsService to maintenance module
  core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/MaintenanceMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/MaintenanceModule.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/PerformanceHintsService.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModule.java
  core/src/test/java/org/hisp/dhis/android/core/maintenance/PerformanceHintsServiceShould.java
Labels: refactor

#494 [ANDROSDK-469] Add created Column to D2Error
  core/src/main/assets/migrations/34.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/D2Error.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorStore.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/D2ErrorTableInfo.java
Labels: enhancement

#493 [ANDROSDK-464] Persist teis after each call
  core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceSyncDownCallRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/D2.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
Labels: enhancement
