Repository dhis2/dhis2-android-sdk, pull requests merged in 2018-08, with the labels that each got.

#338 Generic call data version manager
  core/src/androidTest/java/org/hisp/dhis/android/core/calls/WipeDBCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/calls/WipeDBCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/common/EventCallFactory.java
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramEndpointCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/user/LogoutCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/user/UserCallMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/calls/AggregatedDataCall.java
  core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
  core/src/main/java/org/hisp/dhis/android/core/common/GenericCallData.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserAuthenticateCall.java
  core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
  core/src/test/java/org/hisp/dhis/android/core/user/UserAuthenticateCallUnitShould.java
Labels: refactor

#341 Program stage feature type
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageModelShould.java
  core/src/main/assets/migrations/15.yaml
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/GenericHandlerBaseImpl.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStage.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageFields.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModel.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModelBuilder.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageShould.java
  core/src/test/resources/program/program_stage.json
Labels: enhancement

#340 androsdk-84: Aggregated - Data Set - CatCombo override (spanner symbol)
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkModelShould.java
  core/src/main/assets/migrations/15.yaml
  core/src/main/assets/migrations/16.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkModel.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManager.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentUidsHelper.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetModelBuilderShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManagerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetShould.java
Labels: enhancement

#343 Organisation unit program link update
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitService.java
  core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallUnitShould.java
Labels: bug

#344 Teis sync down call
  core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceSyncDownCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceSyncDownCallRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/D2.java
  core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstanceSyncDownCall.java
Labels: enhancement

#346 Organisation unit program link handler
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkModel.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkStore.java
  core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Labels: bug

#347 Organisation unit data set link handler
  core/src/androidTest/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/calls/MetadataCall.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetOrganisationUnitLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetOrganisationUnitLinkStore.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentCall.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManager.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCall.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
  core/src/test/java/org/hisp/dhis/android/core/common/MetadataCallShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManagerShould.java
  core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Labels: enhancement

#348 Data set data element indicator link handlers
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetDataElementLinkStore.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentCall.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManager.java
  core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorLinkStore.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetParentLinkManagerShould.java
Labels: enhancement

#349 Program data set not org unit linked
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandler.java
  core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
Labels: enhancement

#351 Reserved values not org unit
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/common/D2ErrorCode.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManager.java
Labels: bug

#352 Tei enrollment 2 30 upload
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
Labels: enhancement

#363 ANDROSDK-328: Download Server Name
  core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoDatabaseMappingShould.java
  core/src/main/assets/migrations/17.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfo.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoFields.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoStore.java
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/SystemInfoTableInfo.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/systeminfo/SystemInfoSamples.java
Labels: enhancement
