Repository dhis2/dhis2-android-sdk, pull requests merged in 2018-07, with the labels that each got.

#284 Data elements share update
  core/src/androidTest/assets/data_elements.json
  core/src/androidTest/assets/program_stages.json
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStore.java
  core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementService.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
  core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandlerShould.java
  core/src/test/resources/data_elements.json
  core/src/test/resources/dataelement/data_element.json
Labels: enhancement

#286 Stetho
  core/build.gradle
  core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/AbsStoreTestCase.java
Labels: enhancement

#289 Tracked entity attribute share update
  core/src/androidTest/assets/programs_complete.json
  core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRendering.java
  core/src/main/java/org/hisp/dhis/android/core/data/api/FieldsConverter.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionRendering.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
  core/src/test/java/org/hisp/dhis/android/core/common/IdentifiableHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/data/api/FieldsConverterShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeShould.java
Labels: enhancement

#290 Socket timeout exception
  core/src/main/java/org/hisp/dhis/android/core/common/APICallExecutor.java
  core/src/main/java/org/hisp/dhis/android/core/common/D2ErrorCode.java
Labels: enhancement

#292 Relationship state
  core/src/main/java/org/hisp/dhis/android/core/common/State.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStore.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceStoreImpl.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
Labels: enhancement

#299 Coordinates fix
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventStoreShould.java
  core/src/main/java/org/hisp/dhis/android/core/common/Coordinates.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
Labels: bug

#297 event-post-two-events-test: add second test, fix old one
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventPostCallRealIntegrationShould.java
Labels: bug

#305 Tei last paging download
  core/src/androidTest/java/org/hisp/dhis/android/core/common/D2Factory.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TeiQuery.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancesEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/utils/services/ApiPagingEngine.java
  core/src/main/java/org/hisp/dhis/android/core/utils/services/Paging.java
  core/src/test/java/org/hisp/dhis/android/core/utils/services/ApiPagingEngineShould.java
Labels: bug

#311 Render type fix
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSection.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionRendering.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
Labels: bug

#309 Real integration test logout
  core/src/androidTest/java/org/hisp/dhis/android/core/MetadataCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/TeisCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceQueryAndDownloadRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/TrackedEntityInstanceQueryCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/UserAuthenticateCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/AggregatedDataCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventWithLimitCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
Labels: bug

#307 Events api paging engine
  core/src/androidTest/java/org/hisp/dhis/android/core/common/EventCallFactory.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventEndpointCallMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventQuery.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventWithLimitCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceWithLimitCall.java
  core/src/test/java/org/hisp/dhis/android/core/event/EventEndpointCallShould.java
  core/src/test/java/org/hisp/dhis/android/core/event/EventQueryShould.java
Labels: bug

#315 Dataset: nested fields are not updated when dataset is not updated
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetService.java
Labels: enhancement

#317 Minor syntax cleaning to improve code readability
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSet.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModel.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionDataElementLinkModelBuilderShould.java
Labels: refactor

#321 Tei query call null pointer exception
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/search/TrackedEntityInstanceQueryCall.java
Labels: bug

#318 Fix missing sections support in data set test
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetShould.java
  core/src/test/resources/dataset/data_set.json
Labels: bug

#320 Fix missing DataElementOperandStore as deletable store
  core/src/main/java/org/hisp/dhis/android/core/calls/WipeDBCallable.java
Labels: bug

#322 Program stage description
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageModelShould.java
  core/src/main/assets/migrations/12.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStage.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModel.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageModelBuilder.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageShould.java
  core/src/test/resources/program/program_stage.json
Labels: enhancement

#323 Tracked entity type style
  core/src/androidTest/assets/tracked_entity_types.json
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityType.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeHandler.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/utils/FillPropertiesTestUtils.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeModelBuilderShould.java
Labels: enhancement

#326 Transactional wipe db
  core/src/main/java/org/hisp/dhis/android/core/calls/WipeDBCallable.java
  core/src/test/java/org/hisp/dhis/android/core/calls/WipeDBCallableShould.java
Labels: bug

#324 Sync down deleted events
  core/src/main/java/org/hisp/dhis/android/core/common/DataOrphanCleanerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/Enrollment.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
  core/src/main/java/org/hisp/dhis/android/core/event/Event.java
  core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandlerShould.java
Labels: bug

#329 Sync up deleted events
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstancePostCallRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/calls/TrackedEntityInstancePostCall.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceService.java
Labels: bug

#332 null-rule-variable-value-bug: fix bug
  core-rules/src/main/java/org/hisp/dhis/rules/RuleEngineExecution.java
Labels: bug

#334 DataElements not saved in Database for program stage section
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStore.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandlerShould.java
Labels: bug
