Repository dhis2/dhis2-android-sdk, pull requests merged in 2019-03, with the labels that each got.

#700 [ANDROSDK-649] Implement ProgramSection filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramSectionCollectionRepositoryMockIntegrationShould.java
  core/src/sharedTest/resources/program/programs.json
Labels: enhancement

#710 [ANDROSDK-699] Remove the unnecessary ModelBuilder classes
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandlerWithTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerWithTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/common/LinkModelHandler.java
  core/src/main/java/org/hisp/dhis/android/core/common/LinkModelHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/ModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/common/Transformer.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteToPostTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitDisplayPathTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
  core/src/main/java/org/hisp/dhis/android/core/settings/SystemSettingCall.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueCallProcessor.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEndpointCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserModelBuilder.java
  core/src/test/java/org/hisp/dhis/android/core/category/CategoryComboHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/common/IdentifiableModelBuilderAbstractShould.java
  core/src/test/java/org/hisp/dhis/android/core/common/ModelBuilderAbstractShould.java
  core/src/test/java/org/hisp/dhis/android/core/common/NameableModelBuilderAbstractShould.java
  core/src/test/java/org/hisp/dhis/android/core/common/ValueTypeRenderingHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataelement/DataElementHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/legendset/LegendSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitCallUnitShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramSectionHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/settings/SystemSettingSplitterShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilderShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceModelBuilderShould.java
Labels: refactor

#714 [ANDROSDK-693] Add ne filter for all types
  core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/EqualityFiltersMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/BooleanFilterConnector.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/DateFilterConnector.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/EnumFilterConnector.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/IntegerFilterConnector.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/StringFilterConnector.java
  core/src/sharedTest/resources/program/program_stages.json
Labels: enhancement

#715 [ANDROSDK-651] Implement ProgramStage filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageSectionCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionTableInfo.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionsCollectionRepository.java
  core/src/sharedTest/resources/program/program_stages.json
Labels: enhancement

#718 [ANDROSDK-703] Avoid double loop handling links
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandler.java
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/LinkSyncHandlerWithTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCategoryOptionEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataInputPeriodEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompulsoryDataElementOperandEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetElementEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/indicator/DataSetIndicatorEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupHandler.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupOptionEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorLegendSetEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionAttributeEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionProgramIndicatorEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkEntityDIModule.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/DataSetHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/dataset/SectionHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramSectionHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandlerShould.java
Labels: enhancement

#720 [ANDROSDK-641] Add program foreign key to ProgramSection program column
  core/src/main/assets/migrations/44.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
Labels: bug

#723 [ANDROSDK-707] Build checks not working with Gradle 5
  build.sh
  core/src/main/java/org/hisp/dhis/android/core/arch/handlers/SyncHandlerBaseImpl.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboUidsSeeker.java
  core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/SafeDateFormat.java
  core/src/main/java/org/hisp/dhis/android/core/configuration/ConfigurationManagerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/data/database/SqliteCheckerUtility.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionSetCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/sms/data/smsrepository/SendingStateReceiver.java
  core/src/main/java/org/hisp/dhis/android/core/utils/UserUtils.java
  core/src/main/java/org/hisp/dhis/android/core/utils/Utils.java
  core/src/main/java/org/hisp/dhis/android/core/utils/services/ProgramIndicatorEngine.java
  core/src/main/java/org/hisp/dhis/android/core/utils/support/math/ExpressionFunctions.java
  core/src/main/java/org/hisp/dhis/android/core/wipe/TableWiper.java
  plugins/android-checkstyle.gradle
  plugins/android-findbugs.gradle
  plugins/android-pmd.gradle
Labels: bug

#729 [ANDROSDK-711] Implement children selection in program
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/children/ChildrenAppenderExecutor.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImpl.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/filters/FilterConnectorFactory.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/object/ReadOnlyObjectRepositoryImpl.java
  core/src/main/java/org/hisp/dhis/android/core/arch/repositories/scope/RepositoryScopeHelper.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramCollectionRepository.java
Labels: enhancement

#747 [ANDROSDK-756] Fix PeriodStoreIntegrationShould
  core/src/androidTest/java/org/hisp/dhis/android/core/period/PeriodStoreIntegrationShould.java
Labels: bug

#751 [ANDROSDK-723] Add ForeignKeyViolationCollectionRepository filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/D2ErrorCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/ForeignKeyViolationCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/maintenance/MaintenanceMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationTableInfo.java
Labels: enhancement

#755 [ANDROSDK-736] Add TrackedEntityTypeAttribute repository and filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityTypeAttributeCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModule.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeAttributeCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeAttributeEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeAttributeTableInfo.java
Labels: enhancement

#756 [ANDROSDK-759] Add CategoryOptions as CategoryOptionCombo children
  core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionComboCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCollectionRepository.java
Labels: enhancement
