Repository dhis2/dhis2-android-sdk, pull requests merged in 2019-02, with the labels that each got.

#592 [ANDROSDK-594] Remove Call and SyncCall and use Callable instead
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryEndpointCallShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/datavalue/DataValueEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/option/OptionSetCallShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramEndpointCallMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCallMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/calls/Call.java
  core/src/main/java/org/hisp/dhis/android/core/calls/EndpointCall.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/GenericCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/ListCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/ListCallFactoryImpl.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/QueryCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/QueryCallFactoryImpl.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/UidsCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/calls/factories/UidsCallFactoryImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/SyncCall.java
  core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataCall.java
  core/src/main/java/org/hisp/dhis/android/core/domain/aggregated/data/AggregatedDataModule.java
  core/src/test/java/org/hisp/dhis/android/core/common/BaseCallShould.java
  core/src/test/java/org/hisp/dhis/android/core/common/EndpointPayloadCallAbstractShould.java
  core/src/test/java/org/hisp/dhis/android/core/event/EventEndpointCallShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramEndpointCallShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramModuleDownloaderShould.java
  core/src/test/java/org/hisp/dhis/android/core/user/AuthorityEndpointCallShould.java
Labels: enhancement

#601 [ANDROSDK-603] Delete not used integration test utils
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CreateCategoryOptionComboUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CreateCategoryOptionUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/option/CreateOptionSetUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/CreateProgramRuleVariableUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/CreateProgramStageDataElementUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/CreateProgramStageSectionProgramIndicatorLinkUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/CreateProgramStageSectionUtils.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/CreateTrackedEntityAttributeValueUtils.java
Labels: refactor

#604 [ANDROSDK-606] Remove remaining Handler create methods
  core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyCollectionRepositoryImplIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/ReadOnlyIdentifiableCollectionRepositoryImplIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataelement/DataElementEndpointCallRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueManagerRealIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCallMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/D2DIComponent.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryHandler.java
  core/src/main/java/org/hisp/dhis/android/core/common/CommonPackageDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleHandler.java
  core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeDeviceRenderingEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementOperandHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationImportHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/datavalue/DataValueImportHandler.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
  core/src/main/java/org/hisp/dhis/android/core/imports/WebResponseHandler.java
  core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/period/PeriodHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageDataElementHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramTrackedEntityAttributeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipConstraintEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipItemHandler.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipPackageDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTypeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityDataValueHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceImportHandler.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserHandler.java
  core/src/test/java/org/hisp/dhis/android/core/event/EventHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramStageHandlerShould.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueHandlerShould.java
Labels: enhancement

#606 [ANDROSDK-607] Review 2.31 coding for version manager
  core/src/main/java/org/hisp/dhis/android/core/systeminfo/DHISVersion.java
Labels: enhancement

#609 [ANDROSDK-586] Implement DataSetCompleteRegistration filters
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompleteRegistrationCollectionRepository.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/server/Dhis2MockServer.java
  core/src/sharedTest/resources/dataset/data_set_complete_registrations.json
  core/src/sharedTest/resources/dataset/data_sets.json
  core/src/sharedTest/resources/datavalue/data_values.json
Labels: enhancement

#612 [ANDROSDK-611] [ANDROSDK-614] Add section repository with filters
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/SectionCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetModule.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionEntityDIModule.java
  core/src/sharedTest/resources/dataset/data_sets.json
Labels: enhancement

#620 [ANDROSDK-621] Remove old method for objectWithoutUidStore creation
  core/src/main/java/org/hisp/dhis/android/core/common/StoreFactory.java
Labels: enhancement

#622 [ANDROSDK-622] Add UserOrganisationUnitChildrenAppender
  core/src/androidTest/java/org/hisp/dhis/android/core/user/UserObjectRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/LinkModelChildStore.java
  core/src/main/java/org/hisp/dhis/android/core/arch/db/stores/LinkModelChildStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/SQLStatementBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitStore.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitChildrenAppender.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkTableInfo.java
  core/src/test/java/org/hisp/dhis/android/core/common/SQLStatementBuilderShould.java
Labels: enhancement

#623 [ANDROSDK-588] Implement Event filters
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventModuleMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventCollectionRepository.java
  core/src/sharedTest/resources/event/events.json
Labels: enhancement

#628 [ANDROSDK-629] Make ModelBuilder a functional interface so instances can be lambda
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryComboHandler.java
  core/src/main/java/org/hisp/dhis/android/core/category/CategoryOptionComboCategoryOptionLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/common/ModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStyleModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/common/ValueTypeRenderingHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetCompulsoryDataElementOperandLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/DataSetOrganisationUnitLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/dataset/SectionGreyedFieldsLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/EnrollmentHandler.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventHandler.java
  core/src/main/java/org/hisp/dhis/android/core/event/EventPersistenceCallFactory.java
  core/src/main/java/org/hisp/dhis/android/core/legendset/LegendSetHandler.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitDisplayPathTransformer.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitOrganisationUnitGroupLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/organisationunit/OrganisationUnitProgramLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionAttributeLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStageSectionProgramIndicatorLinkModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserModelBuilder.java
  core/src/main/java/org/hisp/dhis/android/core/user/UserOrganisationUnitLinkModelBuilder.java
Labels: enhancement

#638 [ANDROSDK-589] Implement TrackedEntityInstance filters
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/MockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepository.java
  core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Labels: enhancement

#639 [ANDROSDK-357] Remove deprecated fields in dataelement (numberType and dimension)
  core/src/androidTest/java/org/hisp/dhis/android/testapp/dataelement/DataElementCollectionRepositoryMockIntegrationShould.java
  core/src/main/assets/migrations/38.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElement.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementFields.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementStore.java
  core/src/main/java/org/hisp/dhis/android/core/dataelement/DataElementTableInfo.java
Labels: enhancement

#643 [ANDROSDK-587] Implement Relationship filters
  core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/relationship/RelationshipTableInfo.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/systeminfo/SystemInfoSamples.java
  core/src/sharedTest/resources/systeminfo/system_info.json
  core/src/sharedTest/resources/trackedentity/tracked_entity_instances.json
Labels: enhancement

#649 [ANDROSDK-659] Delete old handler classes
  core/src/main/java/org/hisp/dhis/android/core/calls/processors/TransactionalNoResourceCallProcessor.java
  core/src/main/java/org/hisp/dhis/android/core/common/GenericHandler.java
  core/src/main/java/org/hisp/dhis/android/core/common/GenericHandlerBaseImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/IdentifiableHandlerImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectWithoutUidHandlerImpl.java
  core/src/test/java/org/hisp/dhis/android/core/common/IdentifiableHandlerShould.java
Labels: enhancement

#653 [ANDROSDK-661] Save all the authorities
  core/src/main/java/org/hisp/dhis/android/core/user/AuthorityCallFetcher.java
Labels: enhancement

#652 [ANDROSDK-652-B] and [ANDROSDK-660] Not call for option groups on 2.29 and delete not downloaded option groups
  core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupEntityDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/option/OptionGroupHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramModuleDownloader.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramModuleDownloaderShould.java
Labels: enhancement

#655 [ANDROSDK-643] Add fields option and optionGroup on ProgramRuleAction
  core/src/main/assets/migrations/40.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleAction.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionFields.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionStore.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleActionTableInfo.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/program/ProgramRuleActionSamples.java
  core/src/sharedTest/resources/program/program_rule_action.json
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramRuleActionShould.java
Labels: enhancement

#661 [ANDROSDK-667] Add missing copyright notices to Java files
  core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/AppContextDIModule.java
  core/src/main/java/org/hisp/dhis/android/core/imports/BaseImportSummaries.java
  core/src/main/java/org/hisp/dhis/android/core/imports/BaseImportSummary.java
  core/src/main/java/org/hisp/dhis/android/core/imports/EnrollmentImportSummaries.java
  core/src/main/java/org/hisp/dhis/android/core/imports/EnrollmentImportSummary.java
  core/src/main/java/org/hisp/dhis/android/core/imports/EventImportSummaries.java
  core/src/main/java/org/hisp/dhis/android/core/imports/EventImportSummary.java
  core/src/main/java/org/hisp/dhis/android/core/imports/ImportSummaries.java
  core/src/main/java/org/hisp/dhis/android/core/imports/ImportSummary.java
  core/src/main/java/org/hisp/dhis/android/core/imports/TEIImportSummaries.java
  core/src/main/java/org/hisp/dhis/android/core/imports/TEIImportSummary.java
  core/src/main/java/org/hisp/dhis/android/core/maintenance/ForeignKeyViolationCollectionRepository.java
  core/src/test/java/org/hisp/dhis/android/core/sms/InitTest.java
  core/src/test/java/org/hisp/dhis/android/core/sms/TestRepositories.java
Labels: enhancement

#660 [ANDROSDK-646] Implement ProgramRule filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleCollectionRepository.java
  core/src/sharedTest/resources/program/program_rules.json
Labels: enhancement

#662 [ANDROSDK-645] Implement ProgramIndicator filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramIndicatorCollectionRepository.java
  core/src/sharedTest/resources/program/programs.json
Labels: enhancement

#664 [ANDROSDK-662] Add formName property to TrackedEntityAttribute
  core/src/main/assets/migrations/42.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttribute.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeFields.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandler.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeModel.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeStore.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeTableInfo.java
  core/src/sharedTest/java/org/hisp/dhis/android/core/data/trackedentity/TrackedEntityAttributeSamples.java
  core/src/test/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeHandlerShould.java
Labels: enhancement

#665 [ANDROSDK-665] Add featureType to Program
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
  core/src/main/assets/migrations/43.yaml
  core/src/main/java/org/hisp/dhis/android/core/data/database/DbOpenHelper.java
  core/src/main/java/org/hisp/dhis/android/core/program/Program.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramCollectionRepository.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramDHISVersionManager.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramFields.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramHandler.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramStore.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramTableInfo.java
  core/src/test/java/org/hisp/dhis/android/core/program/ProgramHandlerShould.java
Labels: enhancement

#668 [ANDROSDK-648] Implement ProgramRuleVariable filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleVariableCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramRuleVariableCollectionRepository.java
  core/src/sharedTest/resources/program/programs.json
Labels: enhancement

#682 Move remaining public access should + fix androidTests
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleActionCollectionRepositoryMockIntegrationShould.java
  core/src/sharedTest/resources/program/program_rules.json
  core/src/sharedTest/resources/program/programs.json
  core/src/test/java/org/hisp/dhis/android/testapp/dataset/SectionDataElementLinkPublicAccessShould.java
  core/src/test/java/org/hisp/dhis/android/testapp/organisationunit/OrganisationUnitProgramLinkPublicAccessShould.java
Labels: bug

#685 [ANDROSDK-683] Prevent multiple syncs in repository mock integration tests
  core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/CollectionRepositoryOneMethodMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/IdentifiableCollectionFiltersMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/arch/repositories/collection/NameableCollectionFiltersMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryComboUidsSeekerMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/category/CategoryModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/data/database/SyncedDatabaseMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/dataset/DataSetModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/event/EventModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/maintenance/MaintenanceMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/program/ProgramModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/relationship/RelationshipCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/systeminfo/SystemInfoModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityInstanceCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityTypeCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/core/user/UserModuleMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryComboCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionComboCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/category/CategoryOptionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/dataelement/DataElementCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/DataSetCompleteRegistrationCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/dataset/SectionCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/datavalue/DataValueCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/event/EventCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramIndicatorCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleActionCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramRuleVariableCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramSectionCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramStageSectionCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/trackedentity/TrackedEntityCollectionRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/user/UserCredentialsObjectRepositoryMockIntegrationShould.java
  core/src/androidTest/java/org/hisp/dhis/android/testapp/user/UserObjectRepositoryMockIntegrationShould.java
Labels: enhancement

#684 [HOT-BUG-FIXING] [ANDROSDK-678] Delete only own element notes
  build.gradle
  core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteUniquenessManager.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueStoreImpl.java
  gradle.properties
Labels: bug

#683 [ANDROSDK-678] Delete only own element notes
  core/src/androidTest/java/org/hisp/dhis/android/core/enrollment/EnrollmentCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/common/LinkModelStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStore.java
  core/src/main/java/org/hisp/dhis/android/core/common/ObjectStoreImpl.java
  core/src/main/java/org/hisp/dhis/android/core/enrollment/note/NoteUniquenessManager.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeReservedValueStore.java
  core/src/main/java/org/hisp/dhis/android/core/trackedentity/TrackedEntityAttributeValueStoreImpl.java
Labels: bug

#696 [ANDROSDK-649] Implement ProgramSection filters
  core/src/androidTest/java/org/hisp/dhis/android/testapp/program/ProgramSectionCollectionRepositoryMockIntegrationShould.java
  core/src/main/java/org/hisp/dhis/android/core/program/ProgramSectionCollectionRepository.java
Labels: enhancement
